/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_startwindow (void);
GtkWidget* create_catwindow (void);
GtkWidget* create_rotatewindow (void);
GtkWidget* create_stampwindow (void);
GtkWidget* create_attachwindow (void);
GtkWidget* create_protectwindow (void);
GtkWidget* create_filechooserdialog (void);
GtkWidget* create_folderchooserdialog (void);
GtkWidget* create_burstwindow (void);
GtkWidget* create_acrodialog (void);
GtkWidget* create_customwindow (void);
