/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *startwindow;
/*
  GtkWidget *catwindow;
  GtkWidget *cat_infileachooserdialog;
  GtkWidget *cat_infilebchooserdialog;
  GtkWidget *cat_infilecchooserdialog;
  GtkWidget *cat_outfilechooserdialog;
*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  startwindow = create_startwindow ();
  gtk_widget_show (startwindow);

/*
  catwindow = create_catwindow ();
  gtk_widget_show (catwindow);
  cat_infileachooserdialog = create_cat_infileachooserdialog ();
  gtk_widget_show (cat_infileachooserdialog);
  cat_infilebchooserdialog = create_cat_infilebchooserdialog ();
  gtk_widget_show (cat_infilebchooserdialog);
  cat_infilecchooserdialog = create_cat_infilecchooserdialog ();
  gtk_widget_show (cat_infilecchooserdialog);
  cat_outfilechooserdialog = create_cat_outfilechooserdialog ();
  gtk_widget_show (cat_outfilechooserdialog);
*/

  gtk_main ();
  return 0;
}

